### ISSUE TITLE
ndigits parameter does not work for numpy float types

### ISSUE THREAD

**Issue by silentsnooc** [iamlikeme/rainflow#2]
Apparantly `rainflow.count_cycles` has issues with numpy float types.

```python
import json

y = json.load(open('data.json'))

print('Works ..')
rainflow.count_cycles(y, ndigits=4)

print('Does not work ..')
rainflow.count_cycles(np.asarray(y), ndigits=4)
```

Converting the array to a numpy array makes count_cycles deliver not the desired result.

*Output:*

```
Works ..
[(0.0015, 14.0),
 (0.0016, 1.0),
 (0.0031, 15.0),
 (0.0046, 20.0),
 (0.0062, 14.0),
 (0.0077, 16.0),
 (0.0093, 12.0),
 (0.0108, 15.0),
 (0.0124, 16.0),
 (0.0139, 12.0),
 (0.0154, 11.0),

Does not work ..
[(0.0015, 14.0),
 (0.0016000000000000001, 1.0),
 (0.0030999999999999999, 15.0),
 (0.0045999999999999999, 20.0),
 (0.0061999999999999998, 14.0),
 (0.0077000000000000002, 16.0),
 (0.0092999999999999992, 12.0),
 (0.010800000000000001, 15.0),
```

See [data.json.zip](https://github.com/iamlikeme/rainflow/files/1022091/data.json.zip)

**Comment by iamlikeme** [comment]
Indeed. Do you feel like to make a pull request?

**Comment by iamlikeme** [comment]
On a second thought... I think things actually work as intended. The difference is how native float and numpy.float64 are displayed. Consider this:
```python
>>> a = 1.1
>>> b = np.float64(a)
>>> a == b
True
>>>a
1.1
>>> b
1.1000000000000001
```

So this is only a display issue. The series values are in fact rounded before counting cycles (as they should be):
```python
>>> len(rainflow.count_cycles(y))
10906
>>> len(rainflow.count_cycles(y, ndigits=4))
6620
```

**Comment by silentsnooc** [comment]
Oh, your're right. Sorry for the false alarm Got a little tricked there! Thanks for clarification - I think this issue can be closed in this case :)
