### ISSUE TITLE
Runtime error: Stop Iteration

### ISSUE THREAD

**Issue by capnjess** [iamlikeme/rainflow#27]
Hi Piotr,

Thanks for your work with this excellent package. I ran into this error while using this package on a time series of about 3 million entries. I changed the 'yield' parts of the code to have 

except StopIteration:
    return
However this did not seem to work. I know this might b more of a stackoverflow question but I was wondering if you knew any quickfix.

Many thanks

**Comment by iamlikeme** [comment]
Hi, can you provide a code snipped that caused the error and the traceback (i.e. the full error message printed by python)?

**Comment by capnjess** [comment]
This is the code :

from collections import defaultdict
counts = defaultdict(float)
for low, high, mult in rf.extract_cycles(Hookload_p1, left = 'TRUE', right ='TRUE'):
    mean = 0.5 * (high + low)  
    rng = high - low  
    counts[(mean, rng)] += mult

Y_rfc = pd.DataFrame([(k[0], k[1], v) for k, v in counts.items()], columns = ['Mean', 'Range', 'Cycle'])    



This is the error:

from collections import defaultdict
counts = defaultdict(float)
for low, high, mult in rf.extract_cycles(Hookload_p1, left = 'TRUE', right ='TRUE'):
    mean = 0.5 * (high + low)  
    rng = high - low  
    counts[(mean, rng)] += mult

Y_rfc = pd.DataFrame([(k[0], k[1], v) for k, v in counts.items()], columns = ['Mean', 'Range', 'Cycle'])
Traceback (most recent call last):

  File "<ipython-input-20-d1f03939701b>", line 3, in <module>
    for low, high, mult in rf.extract_cycles(Hookload_p1, left = 'TRUE', right ='TRUE'):

  File "C:\Users\Public\Anaconda3\lib\site-packages\rainflow.py", line 69, in wrapper
    for low, high, mult in func(*args, **kwargs):

  File "C:\Users\Public\Anaconda3\lib\site-packages\rainflow.py", line 98, in extract_cycles
    for x in reversals(series, left=left, right=right):

RuntimeError: generator raised StopIteration

**Comment by iamlikeme** [comment]
What is the type of `Hookload_p1`?

**Comment by capnjess** [comment]
Hookload_p1 is a float64

**Comment by iamlikeme** [comment]
I meant to ask what is the type of `Hookload_p1` itself, not the types of its values. It must be some sort of iterable. I suspect `Hookload_p1` is a generator and it has an implementation error. The RuntimeError you mention happens in cases like this:

```python
def gen(n):
    for i in range(n):
        yield 10 * i
    raise StopIteration  # This line will cause an error

list(gen(5))
# RuntimeError: generator raised StopIteration
```

**Comment by capnjess** [comment]
> I meant to ask what is the type of `Hookload_p1` itself, not the types of its values. It must be some sort of iterable. I suspect `Hookload_p1` is a generator and it has an implementation error. The RuntimeError you mention happens in cases like this:
> 
> ```python
> def gen(n):
>     for i in range(n):
>         yield 10 * i
>     raise StopIteration  # This line will cause an error
> 
> list(gen(5))
> # RuntimeError: generator raised StopIteration
> ```

Hookload_p1 is a  time series of load values from a structural crane member. The values vary from 50t to 300/400 t and this occurs randomly.

**Comment by iamlikeme** [comment]
What do you see when you type `type(Hookload_p1)` in a Python console?

**Comment by capnjess** [comment]
Hi,

It shows  "pandas.core.frame.DataFrame"

**Comment by iamlikeme** [comment]
I see what causes the problem now. Function `rainflow.extract_cycles` expects its first argument to be a sequence of numbers, but a pandas DataFrame is not a sequence of numbers. If you iterate over a DataFrame you get the list of column names, e.g.:

```python
# Create a dataframe with one column called "load"
df = pd.DataFrame.from_dict({"load": [0, -2, 1, -3, 5, -1, 3, -4, 4, -2, 0]})                                                                 

type(df)                                                               
# pandas.core.frame.DataFrame

for item in df: 
    print(item) 
# load

list(rainflow.extract_cycles(df))
# RuntimeError: generator raised StopIteration
```

The correct usage is to pass a specific column from the DataFrame to `extract_cycles`:

```python
list(rainflow.extract_cycles(df.load))
# [(-2, 1, 0.5),
#  (-3, 1, 0.5),
#  (-1, 3, 1.0),
#  (-3, 5, 0.5),
#  (-4, 5, 0.5),
#  (-4, 4, 0.5),
#  (-2, 4, 0.5)]
```
