### ISSUE TITLE
Inconsistent behaviour of binsize and nbins

### ISSUE THREAD

**Issue by iamlikeme** [iamlikeme/rainflow#42]
Hi @gsokoll. I think that binning with parameters `nbins` and `binsize` yields inconsistent results. Since you contributed the feature (#22) I thought I will check with you first.

In the unit tests we have the following cycle counts for series `[-2, 1, -3, 5, -1, 3, -4, 4, -2]`:

range | count
------|------
3 | 0.5
4 | 1.5
6 | 0.5
8 | 1.0
9 | 0.5

With `binsize=3` or `nbins=3` the current behavious results in:

range | bin | count
------|----|------
3 | [0, 3) | 0.0
6 | [3, 6) | 2.0
9 | [6, 9] | 2.0

Since the cycle with range 9 went into bin (6 to 9) I would expect cycle with range 3 to go to bin (0 to 3). However, it went to bin (3, 6). More generally, the bins are inconsistent with respect to which edges are included in the bins. The first two bins are closed on the left side and open on the right,
while the last bin is closed on both sides.

I think the result should be:

range | bin | count
------|-----|------
3 | (0, 3] | 0.5
6 | (3, 6] | 2.0
9 | (6, 9] | 1.5

Here, each bin is open on the left side and closed on the right.

Do you agree that the unit tests should be updated? If yes, I have a working implementation that I could merge.

**Comment by gsokoll** [comment]
My initial reaction is this is likely due to floating point representation but I will look further.  I am not familiar with your description of the bins being open or closed at each side.

**Comment by gsokoll** [comment]
Ok, I have looked more carefully.  Am I correct in understanding that by "open on the left, closed on the right" you mean includes lower bound and excludes upper bound ?  This is consistent with general Python ranges, eg numpy.random.uniform uses this convention.  And yes, I specifically included a check to include any ranges which are equal to the upper bound of the largest bin as an edge case.

But given that a range of 0.0 is not possible in rainflow counts, then it would be reasonable to use bins which are defined as excluding the lower bound and including the upper bound.  If you have an working implementation for this, then feel free to merge.
