### ISSUE TITLE
Feature: Rainflow Matrix

### ISSUE THREAD

**Issue by silentsnooc** [iamlikeme/rainflow#6]
I would love to see the method described [here](https://community.plm.automation.siemens.com/t5/Testing-Knowledge-Base/Rainflow-Counting/ta-p/383093) in this library.

Is there a chance this could happen? :)

**Comment by iamlikeme** [comment]
I suggest that you fork the repo, implement the new method and make a pull request. You can start by writing a draft of the logic and a unit test. (Unfortunately, your link provides no numerical example with an answer... Maybe you have some example from your work or other sources that could be used for testing?)

We can then work together on sewing it together with the rest of the library. In it's current shape it is not designed to support different cycle counting algorithms, but I will be glad to rework it.

**Comment by ramakrse** [comment]
Me too, low to see such capability. Right now, this library gives range and count, it would be nice to extend to return range, mean with cycle count.

**Comment by silentsnooc** [comment]
@ramakrse For now I could recommend https://github.com/Inqbus/inqbus.rainflow which provides this functionality.

**Comment by iamlikeme** [comment]
Hey @silentsnooc and @ramakrse. I made a pull request in an attempt to address your suggestion. It makes possible to extract cycle lows and highs. With that you can create a matrix or a from-to matrix yourself. Does it work for you?
