### ISSUE TITLE
New BUG

### ISSUE THREAD

**Issue by Kyle6699** [iamlikeme/rainflow#60]
Hi,

I found a bug in this module:
![image](https://user-images.githubusercontent.com/53243439/144536467-6b516c31-a967-435e-b774-2f6e8031902f.png)

**Comment by iamlikeme** [comment]
Hi, I am not sure if I see the bug. Let's take for example:

```python
max(series) == 10
min(series) == 0
nbins == 2

binsize = (max(series) - min(series)) / nbins  # == 5.0
rng = max(series) - min(series)  # == 10
```

If I plug in these numbers into formula for `n` in line 160 I get `n == 2` and not `nbins + 1 == 3` as you suggest:

```math
n = int(math.ceil(10 / 5.0)) # == 2
```

Can you provide an example case which demonstrated the error?

**Comment by Kyle6699** [comment]
![image](https://user-images.githubusercontent.com/53243439/144812915-7383f6c9-8ba7-43ee-aa0a-2ecc7c95a38d.png)
max_series = 3517.860166127188
min_series = -3093.4966492094213
nbins = 100
binsize = (max_series - min_series) / nbins
int(math.ceil((max_series - min_series) / binsize))

**Comment by Kyle6699** [comment]
> ![image](https://user-images.githubusercontent.com/53243439/144812915-7383f6c9-8ba7-43ee-aa0a-2ecc7c95a38d.png) max_series = 3517.860166127188 min_series = -3093.4966492094213 nbins = 100 binsize = (max_series - min_series) / nbins int(math.ceil((max_series - min_series) / binsize))

I think the reason is floating-point accuracy from python.

**Comment by iamlikeme** [comment]
Thank you for reporting the bug and providing a test case :clap::clap:
New version 3.1.1 with a bugfix is now available on PyPI.
