### ISSUE TITLE
Why First and Last Point was not yielded?

### ISSUE THREAD

**Issue by marscarl59** [iamlikeme/rainflow#9]
It is a question, not a issue. It is noticed "The generator never yields   the first and the last points in the series." 
Would it be better to yield first and last point as well?

**Comment by iamlikeme** [comment]
You can find explanation in #4 
Now that you mention it, I think it might be useful to control this behavior with a keyword argument.

**Comment by iamlikeme** [comment]
I added keyword arguments `left` and `right` which allow you to treat the first and the last points as reversals (i.e. they would be yielded by the `reversals` generator). See #10.

**Comment by iamlikeme** [comment]
Published to PyPI as v2.1.1
